apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cells.fullname" . }}-issuer
  namespace: {{.Release.Namespace | quote }}
  labels: {{- include "cells.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
  annotations:
    kubernetes.io/service-account.name: {{ include "cells.serviceAccountName" . }}
type: kubernetes.io/service-account-token
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: vault-issuer
  namespace: {{.Release.Namespace | quote }}
  labels: {{- include "cells.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  vault:
    server: {{ include "cells.httpVaultURL" . }}
    path: pki/sign/application
    auth:
      kubernetes:
        mountPath: /v1/auth/kubernetes
        role: app
        secretRef:
          name: {{ include "cells.fullname" . }}-issuer
          key: token
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "cells.etcdName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "cells.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  secretName: {{ include "cells.etcdName" . }}-tls
  issuerRef:
    name: vault-issuer
  commonName: "*.{{ include "cells.serviceDomain" . }}"
  usages:
    - server auth
    - client auth
  #dnsNames:
  #  - {{ include "cells.etcdHost" . }}